AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Template SAM for Bonos backend
#######################################################################################################
#
#  Parameters
#
#######################################################################################################
Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
  FlowAccessNodeHost:
    Type: String
    Default: access.devnet.nodes.onflow.org
  FlowAccessNodePort:
    Type: String
    Default: 9000
  ServiceAccountAddress:
    Type: String
    NoEcho: true
  PrivateKey:
    Type: String
    NoEcho: true
  FindCircleSchedule:
    Type: String
    Default: rate(1 minute)
#######################################################################################################
#
#  Globals
#
#######################################################################################################
Globals:
  Function:
    Runtime: python3.9
    Handler: app.lambda_handler
    MemorySize: 128
    Timeout: 60
Resources:
#######################################################################################################
#
#  Resources / Lambda Functions
#
#######################################################################################################
  FindCirclesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/find_circles
      Environment:
        Variables:
          HOST: !Ref FlowAccessNodeHost
          PORT: !Ref FlowAccessNodePort
          ACCOUNT_ADDRESS: !Ref ServiceAccountAddress
          PRIVATE_KEY: !Ref PrivateKey
      Events:
        FindCirculesScheduleEvent:
          Type: Schedule
          Properties:
            Description: Schedule for finding circles
            Enabled: true
            Schedule: !Ref FindCircleSchedule    
#######################################################################################################
#
#  Outputs
#
#######################################################################################################
#Outputs:
